### ISSUE TITLE
Create Inventory Page

### ISSUE THREAD

**Issue by lag2993** [smcgarr13/Randys-Booth-Co#14]
## User Story
For a company handling different booth build orders I need a page that will list inventory with corresponding information about that item

## Acceptance Criteria
When I click on the inventory link, then I am redirected to a page showing what is kept in the inventory.

For each inventory item it should demonstrate the following information:
- Item ID
- Item Name
- Item Number
- Item Price
- Quantity In-Stock
- Available Quantity
- Category Name
- Active Projects (linked to inventory Item)

**Comment by smcgarr13** [comment]
This has been completed
