### ISSUE TITLE
Create Inventory Model

### ISSUE THREAD

**Issue by lag2993** [smcgarr13/Randys-Booth-Co#2]
## User Story
For a company handling different booth build orders I need a database that will store an object called "Inventory" that will contain information on inventory stock. 

## Acceptance Criteria
When I  create a model called Inventory  it should contain the following information:

- Item ID
- Item Name
- Item Number
- Item Price
- Quantity In-Stock
- Available Quantity
- Category Name
- Active Projects (linked to inventory Item)

**Comment by smcgarr13** [comment]
This has been completed
