### ISSUE TITLE
Create CSS

### ISSUE THREAD

**Issue by lag2993** [smcgarr13/Randys-Booth-Co#20]
## User Story
For a company handling different booth build orders I need an application that has a polished UI and is easy to navigate.

## Acceptance Criteria
It is done when:

- CSS/style mimics clients current website
- There is a header & footer (partials)
- it has a polished UI
- It's responsive
- It's interactive (i.e., accept and respond to user input)

**Comment by smcgarr13** [comment]
This has been completed
