### ISSUE TITLE
Create login.js file

### ISSUE THREAD

**Issue by lag2993** [smcgarr13/Randys-Booth-Co#22]
For a company handling different booth build orders I need a database interface that stores employee user information as a  means of security. 

When I attempt to login the application will take information from inputs. 

When the login form confirms that the information matches database the user will be redirected to the main employee page. 

When the user does not have information stored, a signup form must be created to store information into the database. 

When users information is not found a warning will be displayed letting them know of the failure.

**Comment by BaldOracle** [comment]
Used what was given to start.
